name: Python application

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  AIRFLOW_UID: 999
  DB_HOST: db_host
  DB_PORT: 9999
  DB_DATABASE: db_database
  DB_USER: db_user
  DB_PASSWORD: db_password
  DB_SCHEMA: db_schema
  ACWT_URL: acwt_url
  ACWT_API_KEY: acwt_api_key

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mentre/requirements_test.txt
        if [ -f mentre/requirements.txt ]; then pip install -r mentre/requirements.txt; fi
    - name: Lint with ruff
      run: ruff check --output-format=github .
    - name: Test with pytest
      run: pytest
